/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test1;

import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


/**
 *
 * @author furat
 */
public class PanelDasboard extends javax.swing.JPanel {
    private Container panelstruk;
    private Container maind599;
    

    /**
     * Creates new form PanelDasboard
     */
    public PanelDasboard() {
        initComponents();
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jTxtFieldNama.setVisible(false);
        jTxtFieldEmail.setVisible(false);
        jTxtFieldHarga.setVisible(false);
        jTxtFieldIdDiscord.setVisible(false);
        jCmbPilihProduk.setVisible(false);
        jComboBox1.setVisible(false);
        jButton5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCmbPilihProduk = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jTxtFieldNama = new javax.swing.JTextField();
        jTxtFieldIdDiscord = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTxtFieldEmail = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jTxtFieldHarga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton4.setText("KELUAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(30, 320, 90, 34);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("BERANDA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 120, 91, 34);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton2.setText("LAYANAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 170, 91, 34);

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setText("TENTANG KAMI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 220, 128, 34);

        jButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton6.setText("KEMBALI");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(30, 270, 90, 34);

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ver.SIRA01");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 420, 90, 20);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 150, 460);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(null);

        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pilih tombol layanan untuk melihat produk yang D599 sediakan");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(60, 130, 520, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ini adalah Dashboard DISCORD 599");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(40, 80, 470, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hallo, Selamat Datang");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 50, 350, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/dcwall01.png"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 460);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 630, 460);

        jPanel4.setLayout(null);

        jCmbPilihProduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Layanan -", "Nitro Discord", "Music Bot D599", "Server Bot D599" }));
        jCmbPilihProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbPilihProdukActionPerformed(evt);
            }
        });
        jPanel4.add(jCmbPilihProduk);
        jCmbPilihProduk.setBounds(20, 250, 252, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Discord");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 170, 80, 20);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Music Bot (Bulanan)");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton5);
        jRadioButton5.setBounds(20, 280, 140, 30);

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Server Bot (Tahunan)");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton8);
        jRadioButton8.setBounds(170, 280, 150, 21);
        jPanel4.add(jTxtFieldNama);
        jTxtFieldNama.setBounds(110, 140, 160, 22);
        jPanel4.add(jTxtFieldIdDiscord);
        jTxtFieldIdDiscord.setBounds(110, 170, 160, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 320, 80, 16);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Nitro (Bulanan)");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1);
        jRadioButton1.setBounds(20, 280, 110, 21);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Menu Pembayaran");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 360, 110, 16);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Nitro Classic (Bulanan)");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton3);
        jRadioButton3.setBounds(280, 280, 170, 21);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email Discord");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 200, 80, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "BCA Virtual Account", "BRI Virtual Account", "Mandiri Virtual Account" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(140, 360, 210, 22);
        jPanel4.add(jTxtFieldEmail);
        jTxtFieldEmail.setBounds(110, 200, 160, 22);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Nitro (Tahunan)");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2);
        jRadioButton2.setBounds(140, 280, 120, 21);

        jButton5.setText("Cetak Struk");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(220, 400, 130, 23);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("MusicBot (Tahunan");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton6);
        jRadioButton6.setBounds(170, 280, 140, 30);

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Server Bot (Bulanan)");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton7);
        jRadioButton7.setBounds(20, 280, 150, 21);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Nitro Classic (Tahunan)");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton4);
        jRadioButton4.setBounds(460, 280, 160, 21);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 140, 70, 20);

        jTxtFieldHarga.setEditable(false);
        jPanel4.add(jTxtFieldHarga);
        jTxtFieldHarga.setBounds(140, 320, 135, 22);

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 35)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Layanan Produk Discord 599");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(20, 40, 500, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/dcwall02.png"))); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(0, 0, 630, 460);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 0, 630, 470);

        jPanel5.setLayout(null);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/dcdoc3.png"))); // NOI18N
        jPanel5.add(jLabel18);
        jLabel18.setBounds(100, 150, 350, 210);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Dheny Puji Laksono (!Den), Fauzan Rizki R (Supeng) dan beberapa orang lainnya.");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(30, 100, 560, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Riczky Pratama (SIRA), Faisal Sidauruk (isalY), Aditya Dharma (UnyxZiv),");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(30, 80, 530, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Discord 599 adalah komunitas discord yang terdiri dari beberapa orang yaitu");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(30, 60, 530, 40);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Apa itu Discord 599 ");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(30, 20, 320, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/knonawa.png"))); // NOI18N
        jPanel5.add(jLabel13);
        jLabel13.setBounds(0, 0, 624, 460);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 0, 630, 460);

        add(jPanel2);
        jPanel2.setBounds(150, 0, 630, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel5.setVisible(false);
        jTxtFieldNama.setVisible(true);
        jTxtFieldEmail.setVisible(true);
        jTxtFieldHarga.setVisible(true);
        jTxtFieldIdDiscord.setVisible(true);
        jCmbPilihProduk.setVisible(true);
        jComboBox1.setVisible(true);
        jButton5.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCmbPilihProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbPilihProdukActionPerformed
        // TODO add your handling code here:

        String selectedValue = (String) jCmbPilihProduk.getSelectedItem();

        if (selectedValue.equals("Nitro Discord")) {

            //ini adalah kumpulan buttongroup1
            jRadioButton1.setVisible(true);
            jRadioButton2.setVisible(true);
            jRadioButton3.setVisible(true);
            jRadioButton4.setVisible(true);

            //ini adalah kumpulan buttongroup2
            jRadioButton5.setVisible(false);
            jRadioButton6.setVisible(false);

            //ini adalah kumpulan buttongroup3
            jRadioButton7.setVisible(false);
            jRadioButton8.setVisible(false);

            //ini adalah kumpulan setHarga
            jTxtFieldHarga.setText("");

        } else if (selectedValue.equals("Music Bot D599")) {

            //ini adalah kumpulan buttongroup1
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
            jRadioButton3.setVisible(false);
            jRadioButton4.setVisible(false);

            //ini adalah kumpulan buttongroup2
            jRadioButton5.setVisible(true);
            jRadioButton6.setVisible(true);

            //ini adalah kumpulan buttongroup3
            jRadioButton7.setVisible(false);
            jRadioButton8.setVisible(false);

            //ini adalah kumpulan setHarga
            jTxtFieldHarga.setText("");

        } else if (selectedValue.equals("Server Bot D599")) {

            //ini adalah kumpulan buttongroup1
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
            jRadioButton3.setVisible(false);
            jRadioButton4.setVisible(false);

            //ini adalah kumpulan buttongroup2
            jRadioButton5.setVisible(false);
            jRadioButton6.setVisible(false);

            //ini adalah kumpulan buttongroup3
            jRadioButton7.setVisible(true);
            jRadioButton8.setVisible(true);

            //ini adalah kumpulan buttongroup1
            jTxtFieldHarga.setText("");

        } else {
            // Kode lain yang ingin Anda tambahkan
        }
    }//GEN-LAST:event_jCmbPilihProdukActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        jTxtFieldHarga.setText("65.000");
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        jTxtFieldHarga.setText("1.487.500");
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:

        jTxtFieldHarga.setText("150.000");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:

        jTxtFieldHarga.setText("75.000");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:

        jTxtFieldHarga.setText("1.470.000");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        //menyimpan inputan dalam variable
        String nama = jTxtFieldNama.getText();
        String id = jTxtFieldIdDiscord.getText();
        String email = jTxtFieldEmail.getText();
        String pilihproduk = jCmbPilihProduk.getSelectedItem().toString();
        String pilihan = "";
        if (jRadioButton1.isSelected()) {
            pilihan = jRadioButton1.getText();
        } else if (jRadioButton2.isSelected()) {
            pilihan = jRadioButton2.getText();
        } else if (jRadioButton3.isSelected()) {
            pilihan = jRadioButton3.getText();
        } else if (jRadioButton4.isSelected()) {
            pilihan = jRadioButton4.getText();
        } else if (jRadioButton5.isSelected()) {
            pilihan = jRadioButton5.getText();
        } else if (jRadioButton6.isSelected()) {
            pilihan = jRadioButton6.getText();
        } else if (jRadioButton7.isSelected()) {
            pilihan = jRadioButton7.getText();
        } else if (jRadioButton8.isSelected()) {
            pilihan = jRadioButton8.getText();
        }

        String harga = jTxtFieldHarga.getText();
        String metode = jComboBox1.getSelectedItem().toString();
        
        
        //------------
        
        if (jTxtFieldNama.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon isi nama terlebih dahulu");
        } else if (jTxtFieldIdDiscord.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon isi id discord terlebih dahulu");
        } else if (jTxtFieldEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon isi email terlebih dahulu");
        } else if (jCmbPilihProduk.getSelectedItem().equals("- Pilih Layanan -")) {
            JOptionPane.showMessageDialog(null, "Mohon pilih layanan terlebih dahulu");
        } else if (jComboBox1.getSelectedItem().equals("-")) {
            JOptionPane.showMessageDialog(null, "Mohon pilih metode pembayaran terlebih dahulu");
        } else {
            boolean isButtonGroupSelected = false;

            if (buttonGroup1.getSelection() != null || buttonGroup2.getSelection() != null || buttonGroup3.getSelection() != null) {
                isButtonGroupSelected = true;
            }

            if (isButtonGroupSelected) {
                // Semua input dan seleksi telah valid
                panelstruk = new PanelStruk(nama, id, email, pilihproduk, pilihan, harga, metode);

                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                frame.setContentPane(panelstruk);
                frame.validate();
            } else {
                JOptionPane.showMessageDialog(null, "Mohon pilih produk terlebih dahulu pada salah satu Layanan");
            }
        }

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        jTxtFieldHarga.setText("680.000");
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        jTxtFieldHarga.setText("680.000");
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:

        jTxtFieldHarga.setText("740.000");
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Tutup frame saat ini
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
    
        // Buka menu awal atau form utama baru
        maind599 form = new maind599();
                
        int width = 790;
        int height = 499;
                
        // Menghitung posisi tengah layar
        int screenWidth = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int screenHeight = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int xPos = (screenWidth - width) / 2;
        int yPos = (screenHeight - height) / 2;
            
        form.setBounds(xPos, yPos, width, height);
        form.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jCmbPilihProduk;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JTextField jTxtFieldEmail;
    private javax.swing.JTextField jTxtFieldHarga;
    private javax.swing.JTextField jTxtFieldIdDiscord;
    private javax.swing.JTextField jTxtFieldNama;
    // End of variables declaration//GEN-END:variables
}
