/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test1;

import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.util.Random;

/**
 *
 * @author furat
 */
public class PanelStruk extends javax.swing.JPanel {
    private Container paneldasboard;

    /**
     * Creates new form PanelStruk
     */
    public PanelStruk(String nama, String id, String email, String pilihproduk, String pilihan, String harga, String metode) {
        initComponents();
        jTextField1.setText(nama);
        jTextField2.setText(id);
        jTextField3.setText(email);
        jTextField4.setText(pilihproduk);
        jTextField5.setText(pilihan);
        jTextField6.setText(harga);
        jTextField7.setText(metode);

        randomCharTxt.setText(generateRandomChar());
        
    }

    PanelStruk() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        randomCharTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama :");
        add(jLabel2);
        jLabel2.setBounds(250, 80, 100, 16);

        jTextField5.setEditable(false);
        add(jTextField5);
        jTextField5.setBounds(380, 210, 160, 22);

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(440, 410, 100, 23);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Layanan : ");
        add(jLabel4);
        jLabel4.setBounds(250, 180, 100, 24);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga :");
        add(jLabel6);
        jLabel6.setBounds(250, 250, 100, 24);

        jTextField4.setEditable(false);
        add(jTextField4);
        jTextField4.setBounds(380, 180, 160, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email Discord : ");
        add(jLabel3);
        jLabel3.setBounds(250, 140, 100, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Struk Pembelian di Discord599");
        add(jLabel8);
        jLabel8.setBounds(250, 30, 293, 27);

        jTextField1.setEditable(false);
        add(jTextField1);
        jTextField1.setBounds(380, 70, 160, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("* Jangan lupa untuk Screenshot struk pembayaran ini, untuk bukti. Terima Kasih! *");
        add(jLabel7);
        jLabel7.setBounds(170, 360, 477, 30);

        jTextField2.setEditable(false);
        add(jTextField2);
        jTextField2.setBounds(380, 110, 160, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipe Layanan : ");
        add(jLabel5);
        jLabel5.setBounds(250, 210, 100, 24);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id Discord : ");
        add(jLabel9);
        jLabel9.setBounds(250, 110, 100, 16);

        jTextField3.setEditable(false);
        add(jTextField3);
        jTextField3.setBounds(380, 140, 160, 22);

        jTextField6.setEditable(false);
        add(jTextField6);
        jTextField6.setBounds(380, 250, 160, 22);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Metode Pembayaran :");
        add(jLabel10);
        jLabel10.setBounds(250, 280, 130, 24);

        jTextField7.setEditable(false);
        add(jTextField7);
        jTextField7.setBounds(380, 280, 160, 22);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("No. Virtual Akun");
        add(jLabel11);
        jLabel11.setBounds(250, 310, 130, 24);

        randomCharTxt.setEditable(false);
        add(randomCharTxt);
        randomCharTxt.setBounds(380, 310, 160, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/dcwall03_1.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -40, 780, 540);
    }// </editor-fold>//GEN-END:initComponents

    private String generateRandomChar() {
        String numbers = "0123456789";
        StringBuilder sb = new StringBuilder();

        Random random = new Random();
        while (sb.length() < 16) { // Ubah 10 sesuai dengan panjang karakter yang Anda inginkan
            int index = random.nextInt(numbers.length());
            char randomChar = numbers.charAt(index);
            sb.append(randomChar);
        }

        return sb.toString();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        paneldasboard = new PanelDasboard();

        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.setContentPane(paneldasboard);
        frame.validate();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField randomCharTxt;
    // End of variables declaration//GEN-END:variables
}
